export enum EMuscleCondition {
  GOOD,
  WEAK,
}

export enum EExerciseType {
  STRETCH,
  STRENGTH,
  MASSAGE,
  ENDURANCE,
  TEST,
}

export enum EMuscleGroup {}

export enum EExerciseDifficulty {
  EASY,
  MEDIUM,
  HARD,
}

export enum ECommentType {
  EXERCISE,
  FOOD,
  COMMENT,
}

export enum EJoint {
  HEAD,
  NECK,
  SHOULDER_CENTER,
  SHOULDER,
  ELBOW,
  WRIST,
  FINGERS_HAND,
  LOW_BACK,
  COCCYGIS,
  HIP,
  KNEE,
  ANKLE,
  FINGERS_FOOT,
}

export enum EMuscleID {
  STERNOHYOID,
  OMOHYOID,
  STERNOCLEIDOMASTEOID,
  SEMISPINALIS_CAPITIS,
  SPLENIUS_CAPITIS,
  LEVATOR_SCAPULAE,
  SCALENES,

  PECTORALIS_MAJOR,
  PECTORALIS_MINOR,
  SERRATUS_ANTERIOR,

  SUPRASPINATUS,
  INFRASPINATUS,
  TERES_MAJOR,
  TERES_MINOR,
  SUBSCAPULARIS,

  RHOMBOID_MINOR,
  RHOMBOID_MAJOR,
  SERRATUS_POSTERIOR,
  LATISSIMUS_DORSI,
  TRAPEZIUS,

  DELTOID,
  CORACOBRACHIALIS,
  BICEPS_BRACHII_SHORT,
  BICEPS_BRACHII_LONG,

  TRICEPS_BRACHII,

  BRACHIALIS,
  PRONATOR_TERES,
  FLEXOR_CARPI_RADIALIS,
  FLEXOR_CARPI_ULNARIS,
  PALMARIS_LONGUS,
  ANCONEUS,
  EXTENSOR_CARPI_RADIALIS_LONGUS,
  EXTENSOR_CARPI_RADIALIS_BREVIS,
  EXTENSOR_DIGITORUM,
  EXTENSOR_POLICIS_LONGUS,
  EXTENSOR_POLICIS_BREVIS,

  RECTUS_ABDOMINIS,
  TRANVERSUS_ABDOMINIS,
  EXTERNAL_OBLIQUE,
  INTERNAL_OBLIQUE,

  PSOAS_MINOR,
  PSOAS_MAJOR,
  ILIACUS,
  ILIOPSOAS,
  SARTORIUS,

  TENSOR_FASCIAE_LATAE,
  RECTUS_FEMORIS,
  VASTUS_LATERALIS,
  VASTUS_MEDIALIS,
  GRACILIS,
  ADDUCTOR_LONGUS,

  GLUTEUS_MAXIMUS,
  GLUTEUS_MEDIUS,
  GLUTEUS_MINIMUS,
  PIRIFORMIS,
  ADDUCTOR_MAGNUS,
  BICEPS_FEMORIS,
  SEMITENDINOSUS,
  SEMIMEMBRANOSUS,

  GASTROCNEMIUS,
  POPLITERIUS,
  PLANTARIS,

  FIBULARIS_LONGUS,
  TIBIALIS_ANTERIOR,
  EXTENSOR_DIGITORUM_LONGUS,
  ETENSOR_HALLUCIS_LONGUS,
  SOLEUS,
  FIBULARIS_TERTIUS,
}
