/*
  Warnings:

  - The values [ILIOPSOAS] on the enum `MuscleID` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "MuscleID_new" AS ENUM ('STERNOHYOID', 'OMOHYOIDS', 'STERNOCLEIDOMASTEOID', 'SEMISPINALIS_CAPITIS', 'SPLENIUS_CAPITIS', 'LEVATOR_SCAPULAE', 'SCALENES', 'PECTORALIS_MAJOR', 'PECTORALIS_MINOR', 'SERRATUS_ANTERIOR', 'SUPRASPINATUS', 'INFRASPINATUS', 'TERES_MAJOR', 'TERES_MINOR', 'SUBSCAPULARIS', 'RHOMBOID_MINOR', 'RHOMBOID_MAJOR', 'SERRATUS_POSTERIOR_SUPERIOR', 'SERRATUS_POSTERIOR_INFERIOR', 'LATISSIMUS_DORSI', 'TRAPEZIUS', 'DELTOID', 'CORACOBRACHIALIS', 'BICEPS_BRACHII_SHORT', 'BICEPS_BRACHII_LONG', 'TRICEPS_BRACHII', 'BRACHIORADIALIS', 'PRONATOR_TERES', 'FLEXOR_CARPI_RADIALIS', 'FLEXOR_CARPI_ULNARIS', 'PALMARIS_LONGUS', 'ANCONEUS', 'EXTENSOR_CARPI_RADIALIS_LONGUS', 'EXTENSOR_CARPI_RADIALIS_BREVIS', 'EXTENSOR_DIGITORUM', 'EXTENSOR_POLICIS_LONGUS', 'EXTENSOR_POLICIS_BREVIS', 'RECTUS_ABDOMINIS', 'TRANVERSUS_ABDOMINIS', 'EXTERNAL_OBLIQUE', 'INTERNAL_OBLIQUE', 'QUADRATUS_LUMBORUM', 'PSOAS_MINOR', 'PSOAS_MAJOR', 'ILIACUS', 'SARTORIUS', 'TENSOR_FASCIAE_LATAE', 'RECTUS_FEMORIS', 'VASTUS_LATERALIS', 'VASTUS_MEDIALIS', 'GRACILIS', 'ADDUCTOR_LONGUS', 'GLUTEUS_MAXIMUS', 'GLUTEUS_MEDIUS', 'GLUTEUS_MINIMUS', 'PIRIFORMIS', 'ADDUCTOR_MAGNUS', 'BICEPS_FEMORIS', 'SEMITENDINOSUS', 'SEMIMEMBRANOSUS', 'GASTROCNEMIUS', 'POPLITERIUS', 'PLANTARIS', 'FIBULARIS_LONGUS', 'TIBIALIS_ANTERIOR', 'EXTENSOR_DIGITORUM_LONGUS', 'ETENSOR_HALLUCIS_LONGUS', 'SOLEUS', 'FIBULARIS_TERTIUS');
ALTER TABLE "Muscle" ALTER COLUMN "name" TYPE "MuscleID_new" USING ("name"::text::"MuscleID_new");
ALTER TYPE "MuscleID" RENAME TO "MuscleID_old";
ALTER TYPE "MuscleID_new" RENAME TO "MuscleID";
DROP TYPE "MuscleID_old";
COMMIT;
